title: "[Idea]: "
labels:
  - enhancement
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem does this idea solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe your idea.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: What other approaches did you evaluate?
