name: Feature Request Form
description: Suggest an idea for this project
title: "[Feature]: "
labels:
  - enhancement
assignees: []

body:
  - type: textarea
    id: problem_summary
    attributes:
      label: Problem Summary
      description: A clear and concise description of what the problem is.
      placeholder: |
        I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you want to happen.
      placeholder: |
        The pipeline should...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain why this feature is important.
      placeholder: |
        This should be developed because...
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: (Optional) Add any other context or screenshots about the feature request.
      placeholder: |
        You should also know...
    validations:
      required: false
